const int pwmpin1 = 8;
const int pwmpin2 = 9;
const int ledPin1 = 24;
const int ledPin2 = 25;
const int ledPin3 = 26;
const int ledPin4 = 27;
int ledsw1 = 28;
int ledsw2 = 29;
int ledsw3 = 30;
int ledsw4 = 31;

const int lowSol = 199;
const int dor = 264;
const int re = 297;
const int mi = 330;
const int pa = 352;
const int paS = 369;
const int sol = 396;
const int la = 440;
const int si = 495;
const int hdo = 528;
const int hre = 587;
const int hmi = 659;

int buttonState = 0;
int value = 0xF0;

void setup() {
    Serial.begin(9600);
    Serial.println("programe start");
    pinMode(pwmpin1, OUTPUT);
    pinMode(pwmpin2, OUTPUT);
    pinMode(ledPin1, OUTPUT);
    pinMode(ledPin2, OUTPUT);
    pinMode(ledPin3, OUTPUT);
    pinMode(ledPin4, OUTPUT);
    pinMode(ledsw1, INPUT);
    pinMode(ledsw2, INPUT);
    pinMode(ledsw3, INPUT);
    pinMode(ledsw4, INPUT);
}

void loop() {
    digitalWrite(ledPin1, HIGH);
    digitalWrite(ledPin2, HIGH);
    digitalWrite(ledPin3, HIGH);
    digitalWrite(ledPin4, HIGH);
    if ((digitalRead(ledsw1) == LOW) && (digitalRead(ledsw2) == HIGH) && (digitalRead(ledsw3) == HIGH) && (digitalRead(ledsw4) == HIGH)) {
        schoolBell();
    } else if ((digitalRead(ledsw1) == HIGH) && (digitalRead(ledsw2) == LOW) && (digitalRead(ledsw3) == HIGH) && (digitalRead(ledsw4) == HIGH)) {
        springOfHomeTown();
    } else if ((digitalRead(ledsw1) == HIGH) && (digitalRead(ledsw2) == HIGH) && (digitalRead(ledsw3) == LOW) && (digitalRead(ledsw4) == HIGH)) {
        nationalAnthem();
    } else if ((digitalRead(ledsw1) == HIGH) && (digitalRead(ledsw2) == HIGH) && (digitalRead(ledsw3) == HIGH) && (digitalRead(ledsw4) == LOW)) {
        bbobbobbo();
    } else {
        beep();
        delay(1000);
    }
}
void beep() {
    digitalWrite(ledPin1, LOW);
    digitalWrite(ledPin2, LOW);
    digitalWrite(ledPin3, LOW);
    digitalWrite(ledPin4, LOW);
    tone(pwmpin2, si);
    delay(500);
    tone(pwmpin2, sol);
    delay(500);
    noTone(pwmpin2);
    digitalWrite(ledPin1, HIGH);
    digitalWrite(ledPin2, HIGH);
    digitalWrite(ledPin3, HIGH);
    digitalWrite(ledPin4, HIGH);
}

void schoolBell() {
    digitalWrite(ledPin1, LOW);
    delay(700);
    digitalWrite(ledPin1, HIGH);
    delay(700);
    tone(pwmpin2, sol);
    delay(500);
    tone(pwmpin2, sol);
    delay(500);
    tone(pwmpin2, la);
    delay(500);
    tone(pwmpin2, la);
    delay(500);
    tone(pwmpin2, sol);
    delay(500);
    tone(pwmpin2, sol);
    delay(500);
    tone(pwmpin2, mi);
    delay(1000);
    tone(pwmpin2, sol);
    delay(500);
    tone(pwmpin2, sol);
    delay(500);
    tone(pwmpin2, mi);
    delay(500);
    tone(pwmpin2, mi);
    delay(500);
    tone(pwmpin2, re);
    delay(2000);
    tone(pwmpin2, sol);
    delay(500);
    tone(pwmpin2, sol);
    delay(500);
    tone(pwmpin2, la);
    delay(500);
    tone(pwmpin2, la);
    delay(500);
    tone(pwmpin2, sol);
    delay(500);
    tone(pwmpin2, sol);
    delay(500);
    tone(pwmpin2, mi);
    delay(1000);
    tone(pwmpin2, sol);
    delay(500);
    tone(pwmpin2, mi);
    delay(500);
    tone(pwmpin2, re);
    delay(500);
    tone(pwmpin2, mi);
    delay(500);
    tone(pwmpin2, dor);
    delay(2000);
    noTone(pwmpin2);
}

void springOfHomeTown() {
    digitalWrite(ledPin2, LOW);
    delay(500);
    digitalWrite(ledPin2, HIGH);
    delay(500);
    digitalWrite(ledPin2, LOW);
    delay(500);
    digitalWrite(ledPin2, HIGH);
    delay(5000);
    tone(pwmpin2, sol);
    delay(500);
    tone(pwmpin2, sol);
    delay(500);
    tone(pwmpin2, mi);
    delay(250);
    tone(pwmpin2, pa);
    delay(250);
    tone(pwmpin2, sol);
    delay(500);
    tone(pwmpin2, la);
    delay(500);
    tone(pwmpin2, la);
    delay(500);
    tone(pwmpin2, sol);
    delay(1000);
    tone(pwmpin2, sol);
    delay(500);
    tone(pwmpin2, hdo);
    delay(500);
    tone(pwmpin2, hmi);
    delay(500);
    tone(pwmpin2, hre);
    delay(250);
    tone(pwmpin2, hdo);
    delay(250);
    tone(pwmpin2, hre);
    delay(2000);
    tone(pwmpin2, hmi);
    delay(500);
    tone(pwmpin2, hmi);
    delay(500);
    tone(pwmpin2, hre);
    delay(500);
    tone(pwmpin2, hre);
    delay(500);
    tone(pwmpin2, hdo);
    delay(500);
    tone(pwmpin2, hre);
    delay(250);
    tone(pwmpin2, hdo);
    delay(250);
    tone(pwmpin2, la);
    delay(500);
    tone(pwmpin2, sol);
    delay(500);
    tone(pwmpin2, sol);
    delay(500);
    tone(pwmpin2, sol);
    delay(500);
    tone(pwmpin2, mi);
    delay(250);
    tone(pwmpin2, re);
    delay(250);
    tone(pwmpin2, dor);
    delay(2000);
    noTone(pwmpin2);
}

void nationalAnthem() {
    digitalWrite(ledPin3, LOW);
    delay(200);
    digitalWrite(ledPin3, HIGH);
    delay(200);
    digitalWrite(ledPin3, LOW);
    delay(200);
    digitalWrite(ledPin3, HIGH);
    delay(200);
    digitalWrite(ledPin3, LOW);
    delay(200);
    digitalWrite(ledPin3, HIGH);
    tone(pwmpin2, re);
    delay(500);
    tone(pwmpin2, sol);
    delay(1000);
    tone(pwmpin2, paS);
    delay(250);
    tone(pwmpin2, mi);
    delay(500);
    tone(pwmpin2, sol);
    delay(500);
    tone(pwmpin2, re);
    delay(500);
    tone(pwmpin2, lowSol);
    delay(500);
    tone(pwmpin2, re);
    delay(500);
    tone(pwmpin2, sol);
    delay(500);
    tone(pwmpin2, la);
    delay(250);
    tone(pwmpin2, si);
    delay(250);
    tone(pwmpin2, hdo);
    delay(800);
    tone(pwmpin2, si);
    delay(250);
    tone(pwmpin2, la);
    delay(1700);
    tone(pwmpin2, hre);
    delay(1000);
    tone(pwmpin2, hdo);
    delay(250);
    tone(pwmpin2, si);
    delay(500);
    tone(pwmpin2, la);
    delay(500);
    tone(pwmpin2, sol);
    delay(500);
    tone(pwmpin2, paS);
    delay(250);
    tone(pwmpin2, mi);
    delay(250);
    tone(pwmpin2, re);
    delay(500);
    tone(pwmpin2, lowSol);
    delay(500);
    tone(pwmpin2, re);
    delay(500);
    tone(pwmpin2, sol);
    delay(500);
    tone(pwmpin2, la);
    delay(250);
    tone(pwmpin2, la);
    delay(250);
    tone(pwmpin2, si);
    delay(500);
    tone(pwmpin2, sol);
    delay(2000);
    noTone(pwmpin2);
}

void bbobbobbo() {
    digitalWrite(ledPin4, LOW);
    delay(500);
    digitalWrite(ledPin4, HIGH);
    delay(500);
    digitalWrite(ledPin4, LOW);
    delay(500);
    digitalWrite(ledPin4, HIGH);
    delay(500);
    digitalWrite(ledPin4, LOW);
    delay(500);
    digitalWrite(ledPin4, HIGH);
    delay(500);
    digitalWrite(ledPin4, LOW);
    delay(500);
    digitalWrite(ledPin4, HIGH);
    tone(pwmpin2, sol);
    delay(250);
    tone(pwmpin2, sol);
    delay(250);
    tone(pwmpin2, sol);
    delay(500);
    tone(pwmpin2, mi);
    delay(250);
    tone(pwmpin2, mi);
    delay(250);
    tone(pwmpin2, dor);
    delay(250);
    tone(pwmpin2, mi);
    delay(250);
    tone(pwmpin2, sol);
    delay(250);
    tone(pwmpin2, hdo);
    delay(500);
    tone(pwmpin2, la);
    delay(1000);
    tone(pwmpin2, sol);
    delay(250);
    tone(pwmpin2, sol);
    delay(250);
    tone(pwmpin2, sol);
    delay(500);
    tone(pwmpin2, la);
    delay(250);
    tone(pwmpin2, la);
    delay(250);
    tone(pwmpin2, sol);
    delay(250);
    tone(pwmpin2, pa);
    delay(250);
    tone(pwmpin2, mi);
    delay(250);
    tone(pwmpin2, pa);
    delay(500);
    tone(pwmpin2, re);
    delay(1000);
    tone(pwmpin2, sol);
    delay(250);
    tone(pwmpin2, sol);
    delay(250);
    tone(pwmpin2, sol);
    delay(500);
    tone(pwmpin2, mi);
    delay(250);
    tone(pwmpin2, mi);
    delay(250);
    tone(pwmpin2, dor);
    delay(250);
    tone(pwmpin2, mi);
    delay(250);
    tone(pwmpin2, sol);
    delay(250);
    tone(pwmpin2, hdo);
    delay(500);
    tone(pwmpin2, la);
    delay(1000);
    tone(pwmpin2, si);
    delay(250);
    tone(pwmpin2, si);
    delay(250);
    tone(pwmpin2, si);
    delay(250);
    tone(pwmpin2, si);
    delay(250);
    tone(pwmpin2, si);
    delay(250);
    tone(pwmpin2, sol);
    delay(250);
    tone(pwmpin2, la);
    delay(250);
    tone(pwmpin2, si);
    delay(250);
    tone(pwmpin2, hdo);
    delay(250);
    tone(pwmpin2, hmi);
    delay(500);
    tone(pwmpin2, hdo);
    delay(1000);
    tone(pwmpin2, dor);
    delay(500);
    tone(pwmpin2, mi);
    delay(500);
    tone(pwmpin2, sol);
    delay(750);
    tone(pwmpin2, hdo);
    delay(250);
    tone(pwmpin2, hdo);
    delay(250);
    tone(pwmpin2, hdo);
    delay(500);
    tone(pwmpin2, la);
    delay(750);
    tone(pwmpin2, sol);
    delay(500);
    tone(pwmpin2, sol);
    delay(500);
    tone(pwmpin2, sol);
    delay(500);
    tone(pwmpin2, mi);
    delay(250);
    tone(pwmpin2, pa);
    delay(250);
    tone(pwmpin2, sol);
    delay(850);
    tone(pwmpin2, dor);
    delay(500);
    tone(pwmpin2, mi);
    delay(500);
    tone(pwmpin2, sol);
    delay(750);
    tone(pwmpin2, hdo);
    delay(500);
    tone(pwmpin2, hdo);
    delay(500);
    tone(pwmpin2, la);
    delay(750);
    tone(pwmpin2, sol);
    delay(500);
    tone(pwmpin2, sol);
    delay(500);
    tone(pwmpin2, sol);
    delay(1000);
    tone(pwmpin2, hre);
    delay(500);
    tone(pwmpin2, hdo);
    delay(500);
    noTone(pwmpin2);
}